=== Procedure: [Management Review Proc. Title] +

*Rev. [Rev Number]* +

*[Full Client Name Reg Caps]*

---

[arabic]
. *[.underline]#SUMMARY#*
[arabic]
.. This procedure defines the process and methods for conducting both
    formal and informal management reviews of the quality management system.

.. The [Specific Title for ISO MR] is responsible for implementation of
    this procedure.

.. Top management is responsible for attending formal management review
    meetings.

. *[.underline]#REVISION AND APPROVAL#*
+
[cols="1,1,3,1",options="header",]
|===
|*Rev.* |*Date* |*Nature of Changes* |*Approved By*
|[Rev Number] |[Date of Issue] |Original issue. |[Procedure Approver Name]
| | | |
| | | |
|===

[arabic, start=3]
. *[.underline]#PROCEDURE: CONDUCTING MANAGEMENT REVIEWS#*
[arabic]
.. Top Management reviews the suitability, adequacy and effectiveness of
    the Quality Management System through two primary methods: a formal
    “Management Review Meeting” held periodically, and ongoing management
    activities conducted throughout the rest of the year.

.. The formal “Management Review Meeting” is held at a minimum of once
    per quarter.[ adjust your desired frequency here.]

.. The minimum attendance for Management Review Meeting shall be the
    [list the titles of those who must attend the MR at a minimum; this must
    include top management]; other employees shall attend as needed to meet
    the requirements of the agenda indicated below.

.. If any attendee is absent, draft minutes will be sent to him/her, for
    review and so that the person may amend the minutes with any additional
    data, notes, opinions or opportunities for improvement they may wish to
    add.

.. This review shall include assessing opportunities for improvement and
    the need for changes to the quality management system, including the
    quality policy and quality objectives.

.. Minutes of the meetings are taken and maintained. The form
    *_Management Review Meeting Minutes_* may be used as a template for the
    records, or may be completed and filed as the finished record.

.. The Management Review Meeting shall include analysis of the following
    inputs:

* review and updating of the COTO Log, including Issues, Risks and Opportunities
* review and updating of the Strategic Plan
* review and updating of process objectives, metrics and KPIs
* review of customer feedback
* review of the CAR system and related trends
* review of internal and external audit results
* review of the performance of external providers;
* review of the adequacy of resources;
* review of the effectiveness of actions taken to address risks and opportunities;
* review of opportunities for improvement.
* review of the Quality Policy for adequacy and to ensure it remains
    consistent with the needs of customers and the industry;
* recommendations for improvement of the quality management system
* follow-up activities from previous Management Reviews
[arabic]
.. The Management Review Meeting shall generate Corrective and/or
    Preventive Action Requests (see procedure *_[Corrective Preventive
    Action Proc. Title]_*), or take other recorded action, as a result of
    review topics in an effort to improve the management system, products,
    processes and services, and to address resource needs.

.. This includes any decisions and actions related to the improvement of
    the effectiveness of the quality management system and its processes,
    improvement of product related to customer requirements, and resource
    needs.

.. Additional informal management review activities are also conducted,
    and include:
+
*UPDATE THE FOLLOWING AS APPLICABLE*
[arabic]
... Updating of some objectives data and trending in real time, and
    making such data available on the company server for constant review.
    This includes product nonconformity data, CAR data, internal audit data,
    and customer complaints.

... Weekly meetings are held with the [who?] to discuss issues and
    problems encountered, and to ensure ongoing compliance with established
    quality objectives.

... Daily, informal meetings between the management team [who?] to ensure
    ongoing compliance with established quality objectives, as well as to
    manage daily processing of orders and manufacturing efficiency.
